### ISSUE TITLE
Confused by how melee weapons should be set up

### ISSUE THREAD

**Issue by jbhaywood** [Gerdofal/foundryvtt-cyberpunkred#31]
It seems like if I create an item of type "weapons" it assumes I'm trying to make a ranged weapon, because all the attributes are for ranged weapons and when do the attack roll it uses ranged weapon stats. But things like rippers and big knucks are weapons too, right? I guess I'm supposed to set those up in the "Combat Setup" section? But then why not add all weapons there, including the ranged weapons? I'm not sure why there are two places to add weapons.

Maybe instead of one "weapons" item type, there should be "melee weapons" and "ranged weapons" types. Or add a place in the attributes section for "cyberware" to set damage dice. Then maybe the "Combat Setup" section could just turn into "Armor".

Just some thoughts. Thanks for putting this together.

**Comment by Gerdofal** [comment]
There is a skill drop-down on the Attributes section of the weapon item. You can choose melee weapon there. The UI is a little ugly right now, so I can understand how you missed it.  That's on the list for improvements this version.

As for Combat Setup, you can also put weapons there if you want to do that instead of use all the items and inventory stuff.  Some people don't like the complexity of an inventory, so you can just put weapons on combat setup. If you don't see the weapons fields and only see the armor fields, see settings to enable what I call "simple combat setup".

**Comment by jbhaywood** [comment]
Ah, I get it now. You're right. I missed a bunch of settings. I think the main confusion came from having both ways of setting up weapons turned on by default. I get that turning off one or the other might mean people never notice that the one that's turned off even exists though. Maybe a short description of the "Settings" section in the readme file would help?

Thanks for the reply. Now that I know what to look for, it all makes sense.

**Comment by Gerdofal** [comment]
Here is the new look of the settings section, thoughts?

![image](https://user-images.githubusercontent.com/6471848/89934193-b1b53980-dbbc-11ea-83f8-7a42a89e5dec.png)

**Comment by jbhaywood** [comment]
The wording is definitely more clear now.
